### ISSUE TITLE
The build is not stopped even the sonarqube quality gate failed

### ISSUE THREAD

**Issue by jvnvenu** [simondel/sonar-buildbreaker-vsts#13]
Sonarqube version 6.7
this extension task version 8
The sonarqube web page showing the quality gate is failed. But this extension doesn't stop the build pipeline.
Log of this extension
Number of analyses in this build: 0
Summary of statusses:

**Comment by simondel** [comment]
Hi! This is a known issue with SonarQube 6.7. If you have a 'Publish Quality Gate' task, that's probably not uploading anything to your summary as well (but it only logs that with Debug enabled)

More info: https://community.sonarsource.com/t/sonarqubebuildsummary-md-file-empty-with-the-publish-quality-gate-result-step-in-azure-devops/13305/2

I'm closing this issue for now because there's nothing I can do about this.
