### ISSUE TITLE
Sonar cloud build breaker is not working in Azure devops pipeline

### ISSUE THREAD

**Issue by Srinivas-raju** [simondel/sonar-buildbreaker-vsts#33]
Hi simondel I added the build breaker task 4 months ago, and it's working fine, but recently the build breaker task has stopped working. The quality gate is failing, but the build breaker didn't recognize
<img width="570" alt="Build breaker version" src="https://github.com/simondel/sonar-buildbreaker-vsts/assets/52461271/86227692-d1ea-41df-b2a6-9bef971d0399">

**Comment by yyf-test** [comment]
The problem is that SonarCloud/SonarQube scanning task for AzureDevops been updated and  changed path to save report-task.txt file. Previously path to the file was based on **$(Build.BuildNumber)**, latest version  based on **$(Build.BuildId)**. 
For quick fix - you could set explicitly path to report-file using **extraProperties** in **SonarCloud Prepare Task**:
`sonar.scanner.metadataFilePath=$(Agent.TempDirectory)/sonar/$(Build.BuildNumber)/test/report-task.txt`
Build Breaker task will find the report-task.txt file there. 
Worked for me

Link to issue I have open few days ago:  https://github.com/simondel/sonar-buildbreaker-vsts/issues/31

**Comment by Srinivas-raju** [comment]
Thanks yyf-test now our issue is resolved

once again thankyou very much
