### ISSUE TITLE
why the sq enpoint need to pass explicitly

### ISSUE THREAD

**Issue by martinmani** [simondel/sonar-buildbreaker-vsts#6]
the endpoint is available as serverUrl in report-task.txt file.
So why we need to pass the endpoint explicitly in the task?
Checking since we dont need to pass the endpoint in task "Publish Quality Gate Result"!

**Comment by simondel** [comment]
In order to retrieve the result, the code needs to authenticate to SonarQube/SonarCloud in most cases (public projects don't need authentication). 

My task is not part of the official SonarQube/SonarCloud extension. This means that I cannot access the endpoint you set in the Prepare Analysis task. The Pulish Quality Gate Result task _is_ part of the official extension so it's allowed to reuse your service connection.
